apiVersion: v1
kind: Pod
metadata:
  name: webapp
  
spec:
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /var/log/nginx
        name: my-vol
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: claim-log-1
